package cn.liuyiyou.shop.entity;

import java.util.Date;

public class Banner {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_banner.banner_id
     *
     * @mbg.generated
     */
    private Short bannerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_banner.type
     *
     * @mbg.generated
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_banner.pic
     *
     * @mbg.generated
     */
    private String pic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_banner.redirect_url
     *
     * @mbg.generated
     */
    private String redirectUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_banner.weight
     *
     * @mbg.generated
     */
    private Short weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_banner.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_banner.last_update
     *
     * @mbg.generated
     */
    private Date lastUpdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_banner.filter_channels
     *
     * @mbg.generated
     */
    private String filterChannels;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_banner.apply_crowd
     *
     * @mbg.generated
     */
    private Integer applyCrowd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_banner.start_time
     *
     * @mbg.generated
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_banner.end_time
     *
     * @mbg.generated
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_banner.pic_v2
     *
     * @mbg.generated
     */
    private String picV2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_banner.width
     *
     * @mbg.generated
     */
    private Integer width;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column base_banner.height
     *
     * @mbg.generated
     */
    private Integer height;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_banner.banner_id
     *
     * @return the value of base_banner.banner_id
     *
     * @mbg.generated
     */
    public Short getBannerId() {
        return bannerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_banner.banner_id
     *
     * @param bannerId the value for base_banner.banner_id
     *
     * @mbg.generated
     */
    public void setBannerId(Short bannerId) {
        this.bannerId = bannerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_banner.type
     *
     * @return the value of base_banner.type
     *
     * @mbg.generated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_banner.type
     *
     * @param type the value for base_banner.type
     *
     * @mbg.generated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_banner.pic
     *
     * @return the value of base_banner.pic
     *
     * @mbg.generated
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_banner.pic
     *
     * @param pic the value for base_banner.pic
     *
     * @mbg.generated
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_banner.redirect_url
     *
     * @return the value of base_banner.redirect_url
     *
     * @mbg.generated
     */
    public String getRedirectUrl() {
        return redirectUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_banner.redirect_url
     *
     * @param redirectUrl the value for base_banner.redirect_url
     *
     * @mbg.generated
     */
    public void setRedirectUrl(String redirectUrl) {
        this.redirectUrl = redirectUrl == null ? null : redirectUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_banner.weight
     *
     * @return the value of base_banner.weight
     *
     * @mbg.generated
     */
    public Short getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_banner.weight
     *
     * @param weight the value for base_banner.weight
     *
     * @mbg.generated
     */
    public void setWeight(Short weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_banner.create_date
     *
     * @return the value of base_banner.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_banner.create_date
     *
     * @param createDate the value for base_banner.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_banner.last_update
     *
     * @return the value of base_banner.last_update
     *
     * @mbg.generated
     */
    public Date getLastUpdate() {
        return lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_banner.last_update
     *
     * @param lastUpdate the value for base_banner.last_update
     *
     * @mbg.generated
     */
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_banner.filter_channels
     *
     * @return the value of base_banner.filter_channels
     *
     * @mbg.generated
     */
    public String getFilterChannels() {
        return filterChannels;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_banner.filter_channels
     *
     * @param filterChannels the value for base_banner.filter_channels
     *
     * @mbg.generated
     */
    public void setFilterChannels(String filterChannels) {
        this.filterChannels = filterChannels == null ? null : filterChannels.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_banner.apply_crowd
     *
     * @return the value of base_banner.apply_crowd
     *
     * @mbg.generated
     */
    public Integer getApplyCrowd() {
        return applyCrowd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_banner.apply_crowd
     *
     * @param applyCrowd the value for base_banner.apply_crowd
     *
     * @mbg.generated
     */
    public void setApplyCrowd(Integer applyCrowd) {
        this.applyCrowd = applyCrowd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_banner.start_time
     *
     * @return the value of base_banner.start_time
     *
     * @mbg.generated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_banner.start_time
     *
     * @param startTime the value for base_banner.start_time
     *
     * @mbg.generated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_banner.end_time
     *
     * @return the value of base_banner.end_time
     *
     * @mbg.generated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_banner.end_time
     *
     * @param endTime the value for base_banner.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_banner.pic_v2
     *
     * @return the value of base_banner.pic_v2
     *
     * @mbg.generated
     */
    public String getPicV2() {
        return picV2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_banner.pic_v2
     *
     * @param picV2 the value for base_banner.pic_v2
     *
     * @mbg.generated
     */
    public void setPicV2(String picV2) {
        this.picV2 = picV2 == null ? null : picV2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_banner.width
     *
     * @return the value of base_banner.width
     *
     * @mbg.generated
     */
    public Integer getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_banner.width
     *
     * @param width the value for base_banner.width
     *
     * @mbg.generated
     */
    public void setWidth(Integer width) {
        this.width = width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base_banner.height
     *
     * @return the value of base_banner.height
     *
     * @mbg.generated
     */
    public Integer getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base_banner.height
     *
     * @param height the value for base_banner.height
     *
     * @mbg.generated
     */
    public void setHeight(Integer height) {
        this.height = height;
    }
}