package cn.liuyiyou.shop.entity;

import java.util.Date;

public class Prod {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod.prod_id
     *
     * @mbg.generated
     */
    private Long prodId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod.prod_name
     *
     * @mbg.generated
     */
    private String prodName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod.key_words
     *
     * @mbg.generated
     */
    private String keyWords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod.brand_id
     *
     * @mbg.generated
     */
    private Integer brandId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod.brand_name
     *
     * @mbg.generated
     */
    private String brandName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod.country_id
     *
     * @mbg.generated
     */
    private String countryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod.cata_id
     *
     * @mbg.generated
     */
    private Integer cataId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod.cata_desc
     *
     * @mbg.generated
     */
    private String cataDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod.spu_attr
     *
     * @mbg.generated
     */
    private String spuAttr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod.status_time
     *
     * @mbg.generated
     */
    private Date statusTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod.album
     *
     * @mbg.generated
     */
    private String album;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod.brief
     *
     * @mbg.generated
     */
    private String brief;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod.create_suid
     *
     * @mbg.generated
     */
    private Long createSuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod.update_logs
     *
     * @mbg.generated
     */
    private String updateLogs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod.last_update
     *
     * @mbg.generated
     */
    private Integer lastUpdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod.pop_status
     *
     * @mbg.generated
     */
    private Byte popStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod.pop_album
     *
     * @mbg.generated
     */
    private String popAlbum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod.pop_describe
     *
     * @mbg.generated
     */
    private String popDescribe;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prod.descp
     *
     * @mbg.generated
     */
    private String descp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod.prod_id
     *
     * @return the value of prod.prod_id
     *
     * @mbg.generated
     */
    public Long getProdId() {
        return prodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod.prod_id
     *
     * @param prodId the value for prod.prod_id
     *
     * @mbg.generated
     */
    public void setProdId(Long prodId) {
        this.prodId = prodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod.prod_name
     *
     * @return the value of prod.prod_name
     *
     * @mbg.generated
     */
    public String getProdName() {
        return prodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod.prod_name
     *
     * @param prodName the value for prod.prod_name
     *
     * @mbg.generated
     */
    public void setProdName(String prodName) {
        this.prodName = prodName == null ? null : prodName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod.key_words
     *
     * @return the value of prod.key_words
     *
     * @mbg.generated
     */
    public String getKeyWords() {
        return keyWords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod.key_words
     *
     * @param keyWords the value for prod.key_words
     *
     * @mbg.generated
     */
    public void setKeyWords(String keyWords) {
        this.keyWords = keyWords == null ? null : keyWords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod.brand_id
     *
     * @return the value of prod.brand_id
     *
     * @mbg.generated
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod.brand_id
     *
     * @param brandId the value for prod.brand_id
     *
     * @mbg.generated
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod.brand_name
     *
     * @return the value of prod.brand_name
     *
     * @mbg.generated
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod.brand_name
     *
     * @param brandName the value for prod.brand_name
     *
     * @mbg.generated
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName == null ? null : brandName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod.country_id
     *
     * @return the value of prod.country_id
     *
     * @mbg.generated
     */
    public String getCountryId() {
        return countryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod.country_id
     *
     * @param countryId the value for prod.country_id
     *
     * @mbg.generated
     */
    public void setCountryId(String countryId) {
        this.countryId = countryId == null ? null : countryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod.cata_id
     *
     * @return the value of prod.cata_id
     *
     * @mbg.generated
     */
    public Integer getCataId() {
        return cataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod.cata_id
     *
     * @param cataId the value for prod.cata_id
     *
     * @mbg.generated
     */
    public void setCataId(Integer cataId) {
        this.cataId = cataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod.cata_desc
     *
     * @return the value of prod.cata_desc
     *
     * @mbg.generated
     */
    public String getCataDesc() {
        return cataDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod.cata_desc
     *
     * @param cataDesc the value for prod.cata_desc
     *
     * @mbg.generated
     */
    public void setCataDesc(String cataDesc) {
        this.cataDesc = cataDesc == null ? null : cataDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod.spu_attr
     *
     * @return the value of prod.spu_attr
     *
     * @mbg.generated
     */
    public String getSpuAttr() {
        return spuAttr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod.spu_attr
     *
     * @param spuAttr the value for prod.spu_attr
     *
     * @mbg.generated
     */
    public void setSpuAttr(String spuAttr) {
        this.spuAttr = spuAttr == null ? null : spuAttr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod.create_time
     *
     * @return the value of prod.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod.create_time
     *
     * @param createTime the value for prod.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod.status
     *
     * @return the value of prod.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod.status
     *
     * @param status the value for prod.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod.status_time
     *
     * @return the value of prod.status_time
     *
     * @mbg.generated
     */
    public Date getStatusTime() {
        return statusTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod.status_time
     *
     * @param statusTime the value for prod.status_time
     *
     * @mbg.generated
     */
    public void setStatusTime(Date statusTime) {
        this.statusTime = statusTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod.album
     *
     * @return the value of prod.album
     *
     * @mbg.generated
     */
    public String getAlbum() {
        return album;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod.album
     *
     * @param album the value for prod.album
     *
     * @mbg.generated
     */
    public void setAlbum(String album) {
        this.album = album == null ? null : album.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod.brief
     *
     * @return the value of prod.brief
     *
     * @mbg.generated
     */
    public String getBrief() {
        return brief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod.brief
     *
     * @param brief the value for prod.brief
     *
     * @mbg.generated
     */
    public void setBrief(String brief) {
        this.brief = brief == null ? null : brief.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod.create_suid
     *
     * @return the value of prod.create_suid
     *
     * @mbg.generated
     */
    public Long getCreateSuid() {
        return createSuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod.create_suid
     *
     * @param createSuid the value for prod.create_suid
     *
     * @mbg.generated
     */
    public void setCreateSuid(Long createSuid) {
        this.createSuid = createSuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod.update_logs
     *
     * @return the value of prod.update_logs
     *
     * @mbg.generated
     */
    public String getUpdateLogs() {
        return updateLogs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod.update_logs
     *
     * @param updateLogs the value for prod.update_logs
     *
     * @mbg.generated
     */
    public void setUpdateLogs(String updateLogs) {
        this.updateLogs = updateLogs == null ? null : updateLogs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod.last_update
     *
     * @return the value of prod.last_update
     *
     * @mbg.generated
     */
    public Integer getLastUpdate() {
        return lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod.last_update
     *
     * @param lastUpdate the value for prod.last_update
     *
     * @mbg.generated
     */
    public void setLastUpdate(Integer lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod.pop_status
     *
     * @return the value of prod.pop_status
     *
     * @mbg.generated
     */
    public Byte getPopStatus() {
        return popStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod.pop_status
     *
     * @param popStatus the value for prod.pop_status
     *
     * @mbg.generated
     */
    public void setPopStatus(Byte popStatus) {
        this.popStatus = popStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod.pop_album
     *
     * @return the value of prod.pop_album
     *
     * @mbg.generated
     */
    public String getPopAlbum() {
        return popAlbum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod.pop_album
     *
     * @param popAlbum the value for prod.pop_album
     *
     * @mbg.generated
     */
    public void setPopAlbum(String popAlbum) {
        this.popAlbum = popAlbum == null ? null : popAlbum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod.pop_describe
     *
     * @return the value of prod.pop_describe
     *
     * @mbg.generated
     */
    public String getPopDescribe() {
        return popDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod.pop_describe
     *
     * @param popDescribe the value for prod.pop_describe
     *
     * @mbg.generated
     */
    public void setPopDescribe(String popDescribe) {
        this.popDescribe = popDescribe == null ? null : popDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prod.descp
     *
     * @return the value of prod.descp
     *
     * @mbg.generated
     */
    public String getDescp() {
        return descp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prod.descp
     *
     * @param descp the value for prod.descp
     *
     * @mbg.generated
     */
    public void setDescp(String descp) {
        this.descp = descp == null ? null : descp.trim();
    }
}