package cn.liuyiyou.shop.mapper;

import cn.liuyiyou.shop.entity.Prod;
import cn.liuyiyou.shop.entity.ProdExample;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ProdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prod
     *
     * @mbg.generated
     */
    long countByExample(ProdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prod
     *
     * @mbg.generated
     */
    int insert(Prod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prod
     *
     * @mbg.generated
     */
    int insertSelective(Prod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prod
     *
     * @mbg.generated
     */
    List<Prod> selectByExampleWithBLOBs(ProdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prod
     *
     * @mbg.generated
     */
    List<Prod> selectByExample(ProdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prod
     *
     * @mbg.generated
     */
    Prod selectByPrimaryKey(Long prodId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prod
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Prod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prod
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Prod record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prod
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Prod record);
}